const roomTypes = [
  {name:'Gaming Room',emoji:'🎮',cat:'entertainment',price:'RM8,000–RM30,000+',img:'neon_cyberpunk_gaming_bedroom.webp',tone:'vivid',desc:'A purpose-built setup for PC, console or streaming with immersive lighting, clean cabling and equipment-first planning.',features:['RGB / smart lighting','Gaming desk & monitor layout','Acoustic panels','Display shelving','Cable management','Audio-reactive lighting']},
  {name:'Romance Room / Couples Retreat',emoji:'💕',cat:'lifestyle',price:'RM5,000–RM18,000+',img:'moody_luxury_bedroom_with_orange_accents.webp',tone:'warm',desc:'A warm, intimate retreat focused on comfort, ambience and premium soft furnishings rather than loud decoration.',features:['Ambient layered lighting','Premium bedding','Curtains & mirrors','Aroma diffuser zone','Soft furnishings','Elegant intimate décor']},
  {name:'Spiritual / Prayer Room',emoji:'🕊️',cat:'wellness',price:'RM4,000–RM15,000+',img:'serene_modern_islamic_prayer_room.webp',tone:'soft',desc:'A respectful, peaceful room designed around the customer’s faith practices, storage needs and preferred religious décor.',features:['Customer-selected religious décor','Prayer / reflection area','Calm lighting','Purposeful storage','Soft flooring options','Peaceful colour palette']},
  {name:'Zen / Meditation Room',emoji:'🧘',cat:'wellness',price:'RM4,000–RM15,000+',img:'serene_zen_tea_room_retreat.webp',tone:'soft',desc:'A low-clutter wellness space that uses natural material cues, warm lighting and calm zoning to help the room feel quieter.',features:['Minimalist layout','Plants & natural textures','Floor seating','Diffusers','Warm indirect lighting','Hidden storage']},
  {name:'Mini Cinema Room',emoji:'🎬',cat:'entertainment',price:'RM12,000–RM45,000+',img:'cinematic_home_theater_with_paramount_screen.webp',tone:'warm',desc:'A compact private cinema with controlled light, comfortable seating and an AV setup planned around the room.',features:['Projector or large display','Blackout treatment','Speaker setup','Cinema seating','Mood lighting','Acoustic improvements']},
  {name:'Music Room',emoji:'🎧',cat:'entertainment',price:'RM10,000–RM40,000+',img:'moody_orange_lit_creator_studio.webp',tone:'warm',desc:'A creative listening or playing environment combining instrument display, storage, audio and acoustic treatment.',features:['Instrument display','Speaker positioning','Acoustic panels','Record / media shelving','Ambient lighting','Cable and equipment storage']},
  {name:'Podcast / Streaming Room',emoji:'🎙️',cat:'work',price:'RM8,000–RM25,000+',img:'moody_orange_lit_creator_studio.webp',tone:'vivid',desc:'A camera-ready workspace for podcasting, live streaming and video production with practical acoustic and lighting design.',features:['Microphone zone','Camera positioning','Backdrop design','Acoustic treatment','Key / fill lighting','Desk & equipment storage']},
  {name:'Home Office Transformation',emoji:'💻',cat:'work',price:'RM6,000–RM22,000+',img:'moody_charcoal_home_office_with_amber_glow.webp',tone:'cool',desc:'A focused, ergonomic workspace that looks professional on calls and works harder for storage and productivity.',features:['Ergonomic desk layout','Office chair planning','Professional backdrop','Task lighting','Storage systems','Cable management']},
  {name:'Study Room',emoji:'📚',cat:'work',price:'RM5,000–RM18,000+',img:'cozy_fantasy_children_s_bedroom_workspace.webp',tone:'soft',desc:'A distraction-reduced learning room built around good task lighting, books, organisation and comfortable desk work.',features:['Study desk','Bookshelves','Task lighting','Whiteboard / planning zone','Organisation systems','Comfortable reading area']},
  {name:'Nature / Jungle Room',emoji:'🌿',cat:'lifestyle',price:'RM6,000–RM20,000+',img:'sunlit_bohemian_jungle_conservatory.webp',tone:'vivid',desc:'A lush botanical room using greenery, wood, earthy materials and natural-feeling light for an indoor escape.',features:['Greenery walls / plants','Wood textures','Earth-tone palette','Natural lighting effects','Botanical décor','Organic soft furnishings']},
  {name:'Luxury Hotel Room',emoji:'✨',cat:'premium',price:'RM12,000–RM35,000+',img:'tropical_eco_luxe_bedroom_retreat.webp',tone:'soft',desc:'A polished bedroom inspired by boutique hotels: layered lighting, premium bedding, tailored curtains and elegant details.',features:['Statement headboard wall','Premium bedding','Bedside lighting','Full-length mirrors','Tailored curtains','Hotel-style accessories']},
  {name:'Dark Luxury Room',emoji:'🖤',cat:'premium',price:'RM12,000–RM35,000+',img:'moody_luxury_bedroom_with_orange_accents.webp',tone:'warm',desc:'A dramatic, sophisticated bedroom using charcoal tones, metallic accents, atmospheric light and statement furniture.',features:['Black / charcoal palette','Gold / metallic accents','Atmospheric lighting','Statement artwork','Premium furniture','Layered textures']},
  {name:'Cute / Pastel Room',emoji:'💗',cat:'lifestyle',price:'RM6,000–RM20,000+',img:'dreamy_pastel_kawaii_bedroom.webp',tone:'soft',desc:'A playful, photo-friendly pastel room with soft textures, flattering lighting and carefully curated display areas.',features:['Pastel palette','Soft lighting','Fluffy rugs','Mirrors','Display shelves','Cute themed décor']},
  {name:'Anime Room',emoji:'👾',cat:'entertainment',price:'RM7,000–RM25,000+',img:'neon_cyberpunk_gaming_bedroom.webp',tone:'vivid',desc:'A collector-friendly anime room with integrated display, lighting and themed décor without losing bedroom function.',features:['Display shelves','Figurine lighting','RGB accents','Poster / art walls','Themed bedding','Collector storage']},
  {name:'Sports Fan Room',emoji:'⚽',cat:'entertainment',price:'RM7,000–RM25,000+',img:'ultimate_sports_man_cave_lounge.webp',tone:'vivid',desc:'A personalised fan cave built around the customer’s club, memorabilia, match viewing and entertainment setup.',features:['Club colour palette','Jersey displays','Memorabilia cases','TV viewing zone','Themed lighting','Lounge seating']},
  {name:'Car Enthusiast Room',emoji:'🚗',cat:'entertainment',price:'RM9,000–RM30,000+',img:'ultimate_sports_man_cave_lounge.webp',tone:'warm',desc:'A motorsport-inspired personal space with model displays, automotive textures and garage-style details.',features:['Automotive artwork','Model-car displays','Racing-inspired furniture','Neon signage','Industrial accents','Display lighting']},
  {name:'Sneaker / Fashion Room',emoji:'👟',cat:'lifestyle',price:'RM10,000–RM35,000+',img:'dreamy_pastel_kawaii_bedroom.webp',tone:'cool',desc:'A boutique-style room that turns shoes and clothing into part of the interior through illuminated organised display.',features:['Illuminated shoe displays','Clothing racks','Mirrors','Custom shelving','Boutique lighting','Dressing zone']},
  {name:'Princess / Glam Room',emoji:'👑',cat:'family',price:'RM8,000–RM28,000+',img:'dreamy_pastel_kawaii_bedroom.webp',tone:'soft',desc:'An elegant glam room with vanity lighting, soft furnishing, organised wardrobe areas and strong statement pieces.',features:['Vanity station','Mirror lighting','Soft furnishings','Wardrobe organisation','Decorative lighting','Statement décor']},
  {name:'Kids Fantasy Room',emoji:'🧸',cat:'family',price:'RM8,000–RM30,000+',img:'cozy_fantasy_children_s_bedroom_workspace.webp',tone:'vivid',desc:'A personalised imaginative room built around a child’s favourite world — space, dinosaurs, ocean, heroes, jungle or an original theme.',features:['Custom theme concept','Feature walls / murals','Play & sleep zoning','Creative lighting','Child-friendly storage','Themed accessories']},
  {name:'Baby / Nursery Room',emoji:'👶',cat:'family',price:'RM7,000–RM25,000+',img:'tropical_eco_luxe_bedroom_retreat.webp',tone:'soft',desc:'A calm nursery designed around safe circulation, storage, feeding, sleep and soothing light.',features:['Cot zone','Changing / storage area','Calming palette','Soft lighting','Feeding chair zone','Personalised décor']},
  {name:'Creative Studio',emoji:'🎨',cat:'work',price:'RM7,000–RM25,000+',img:'moody_orange_lit_creator_studio.webp',tone:'vivid',desc:'A flexible room for artists and makers with adjustable lighting, accessible tools and surfaces that can handle creative work.',features:['Art / maker desk','Equipment storage','Inspirational wall','Adjustable lighting','Display area','Organised supply storage']},
  {name:'Content Creator Room',emoji:'📸',cat:'work',price:'RM9,000–RM30,000+',img:'moody_orange_lit_creator_studio.webp',tone:'vivid',desc:'A multi-angle room designed to look good on camera with several usable backgrounds, lighting positions and prop storage.',features:['Multiple filming backgrounds','Ring / video lighting','Prop storage','Camera positions','Acoustic treatment options','Editing workstation']},
  {name:'Bachelor Pad',emoji:'👔',cat:'lifestyle',price:'RM10,000–RM35,000+',img:'moody_luxury_bedroom_with_orange_accents.webp',tone:'cool',desc:'A contemporary, masculine retreat that blends bedroom comfort, entertainment and smart storage.',features:['Contemporary furniture','Entertainment zone','Mood lighting','Bar-style feature options','Smart storage','Statement wall']},
  {name:'Beauty / Makeup Room',emoji:'💄',cat:'lifestyle',price:'RM7,000–RM25,000+',img:'dreamy_pastel_kawaii_bedroom.webp',tone:'soft',desc:'A flattering, organised beauty room built around mirror lighting, product storage and a comfortable preparation station.',features:['Illuminated vanity','Makeup storage','Large mirrors','Product display','Flattering lighting','Comfortable seating']},
  {name:'Walk-In Wardrobe Transformation',emoji:'👗',cat:'premium',price:'RM12,000–RM45,000+',img:'tropical_eco_luxe_bedroom_retreat.webp',tone:'soft',desc:'A dressing-room transformation focused on custom storage, visibility, mirrors, shoe display and premium lighting.',features:['Custom wardrobes / racks','Shoe displays','Full-length mirrors','Integrated lighting','Accessory storage','Dressing area']},
  {name:'Chill Lounge Room',emoji:'☕',cat:'lifestyle',price:'RM6,000–RM22,000+',img:'sunlit_bohemian_jungle_conservatory.webp',tone:'warm',desc:'A comfortable escape for conversation, music, reading or doing absolutely nothing — intentionally.',features:['Sofa / beanbag seating','Coffee table','Ambient lighting','Speakers','Artwork','Relaxed soft furnishings']},
  {name:'Party Room',emoji:'🪩',cat:'entertainment',price:'RM10,000–RM35,000+',img:'neon_cyberpunk_gaming_bedroom.webp',tone:'vivid',desc:'A private entertaining space built around music, reactive lighting, durable finishes and social seating.',features:['Music-reactive LEDs','Speaker system','Disco / effect lighting','Neon signs','Entertaining layout','Durable surfaces']},
  {name:'Productivity Room',emoji:'🧠',cat:'work',price:'RM5,000–RM18,000+',img:'moody_charcoal_home_office_with_amber_glow.webp',tone:'cool',desc:'A disciplined workstation with planning surfaces, organisation and lighting chosen to reduce visual distraction.',features:['Clean workstation','Planning boards','Task lighting','Organisation systems','Hidden cable routing','Minimal distraction layout']},
  {name:'Galaxy / Space Room',emoji:'🌌',cat:'family',price:'RM7,000–RM25,000+',img:'neon_cyberpunk_gaming_bedroom.webp',tone:'vivid',desc:'An immersive futuristic room using projected stars, LED effects and space-inspired surfaces.',features:['Galaxy projector','LED strips','Star ceiling effects','Futuristic décor','Themed wall design','Display lighting']},
  {name:'Resort / Bali Room',emoji:'🏝️',cat:'wellness',price:'RM8,000–RM28,000+',img:'tropical_eco_luxe_bedroom_retreat.webp',tone:'soft',desc:'A warm tropical retreat combining natural wood, woven textures, greenery and resort-like ambient lighting.',features:['Natural wood details','Plants','Woven décor','Warm lamps','Tropical textures','Resort-inspired bedding']},
  {name:'Fantasy Room',emoji:'🧙',cat:'family',price:'RM10,000–RM40,000+',img:'cozy_fantasy_children_s_bedroom_workspace.webp',tone:'vivid',desc:'A fully themed room inspired by medieval, gothic, magical or enchanted worlds, designed as an original customer-specific concept.',features:['Original fantasy theme','Atmospheric wall treatment','Custom lighting','Display pieces','Themed furniture details','Immersive accessories']},
  {name:'Airbnb Room Makeover',emoji:'🏨',cat:'premium',price:'RM6,000–RM25,000+',img:'tropical_eco_luxe_bedroom_retreat.webp',tone:'soft',desc:'A photogenic, practical refresh designed to help a rental room present better in listings and guest photos.',features:['Listing-friendly styling','Durable furniture','Statement photo corner','Lighting improvements','Storage for guests','Easy-maintenance finishes']},
  {name:'Complete Bedroom Rescue',emoji:'🛏️',cat:'premium',price:'RM6,000–RM30,000+',img:'moody_black_and_orange_gaming_retreat.webp',tone:'warm',desc:'For customers who know the room needs help but do not know what style to choose. TRP develops the direction around personality, use and budget.',features:['Room diagnosis','Style recommendation','Priority-based budget plan','Furniture & lighting plan','Decorative transformation','Full TRP coordination']}
];

const grid = document.getElementById('roomGrid');
const formRoom = document.getElementById('formRoom');
function renderRooms(filter='all'){
  const list = filter==='all' ? roomTypes : roomTypes.filter(r=>r.cat===filter);
  grid.innerHTML = list.map((r)=>`<article class="room-card tone-${r.tone}" data-name="${r.name.replaceAll('"','&quot;')}">
    <img loading="lazy" src="assets/images/${r.img}" alt="Concept visual for ${r.name}" />
    <div class="room-card-content"><div class="room-card-top"><span class="room-emoji">${r.emoji}</span><span class="room-price">${r.price}</span></div>
    <h3>${r.name}</h3><p>${r.desc}</p><button type="button" data-room="${encodeURIComponent(r.name)}">View concept <span>→</span></button></div>
  </article>`).join('');
}
renderRooms();
roomTypes.forEach(r=>{const o=document.createElement('option');o.value=r.name;o.textContent=`${r.emoji} ${r.name} — ${r.price}`;formRoom.appendChild(o)});

document.getElementById('filters').addEventListener('click',e=>{const b=e.target.closest('[data-filter]');if(!b)return;document.querySelectorAll('.filter-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderRooms(b.dataset.filter)});

const modal=document.getElementById('roomModal');
function openRoom(name){const r=roomTypes.find(x=>x.name===name);if(!r)return;document.getElementById('modalImage').src=`assets/images/${r.img}`;document.getElementById('modalImage').alt=`Concept visual for ${r.name}`;document.getElementById('modalCategory').textContent=r.cat.replace('work','work & create');document.getElementById('modalEmoji').textContent=`${r.emoji} ROOM CONCEPT`;document.getElementById('modalTitle').textContent=r.name;document.getElementById('modalPrice').textContent=`Estimated ${r.price}`;document.getElementById('modalDescription').textContent=r.desc;document.getElementById('modalFeatures').innerHTML=r.features.map(f=>`<li>${f}</li>`).join('');formRoom.value=r.name;modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.classList.add('modal-open')}
grid.addEventListener('click',e=>{const b=e.target.closest('[data-room]');if(b)openRoom(decodeURIComponent(b.dataset.room))});
function closeModal(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.classList.remove('modal-open')}
document.querySelectorAll('[data-close-modal]').forEach(el=>el.addEventListener('click',closeModal));document.getElementById('modalStart').addEventListener('click',closeModal);document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});

const navToggle=document.querySelector('.nav-toggle'),nav=document.querySelector('.main-nav');navToggle.addEventListener('click',()=>{const open=nav.classList.toggle('open');navToggle.setAttribute('aria-expanded',open)});nav.addEventListener('click',e=>{if(e.target.tagName==='A')nav.classList.remove('open')});

const projectForm=document.getElementById('projectForm'), briefWrap=document.getElementById('briefWrap'), briefOutput=document.getElementById('briefOutput');
projectForm.addEventListener('submit',e=>{e.preventDefault();const chosen=roomTypes.find(r=>r.name===formRoom.value);const brief=`TRP — THE ROOM PROJECT\nDRAFT CUSTOMER PROJECT BRIEF\n\nRoom concept: ${formRoom.value}\nIndicative website range: ${chosen?.price || 'To be assessed'}\nLocation: ${document.getElementById('formLocation').value}\nRoom size: ${document.getElementById('formSize').value}\nWorking budget: ${document.getElementById('formBudget').value}\nDesired scope: ${document.getElementById('formScope').value}\n\nCustomer vision / must-haves:\n${document.getElementById('formVision').value || 'Not provided yet'}\n\nIMPORTANT: This is an initial project brief, not a quotation. Final scope and pricing require TRP assessment and confirmation from the relevant specialist partners and suppliers.`;briefOutput.textContent=brief;briefWrap.hidden=false;briefWrap.scrollIntoView({behavior:'smooth',block:'center'})});
document.getElementById('copyBrief').addEventListener('click',async e=>{await navigator.clipboard.writeText(briefOutput.textContent);const old=e.target.textContent;e.target.textContent='Copied ✓';setTimeout(()=>e.target.textContent=old,1400)});

document.getElementById('year').textContent=new Date().getFullYear();
const io=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');io.unobserve(entry.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>io.observe(el));
